config/routes.rb
SuperScraper::Application.routes.draw do
  resources :events_parsers

  resources :event_aggs

  root "event_aggs#index"

end

app/models/event_agg.rb
class EventAgg < ActiveRecord::Base
  has_one :events_parser
end

app/models/events_parser.rb
class EventsParser < ActiveRecord::Base
  belongs_to :event_agg
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/event_aggs_controller.rb
class EventAggsController < ApplicationController
  before_action :set_event_agg, only: [:show, :edit, :update, :destroy]

  # GET /event_aggs
  # GET /event_aggs.json
  def index
    @event_aggs = EventAgg.all
  end

  # GET /event_aggs/1
  # GET /event_aggs/1.json
  def show
  end

  # GET /event_aggs/new
  def new
    @event_agg = EventAgg.new
  end

  # GET /event_aggs/1/edit
  def edit
  end

  # POST /event_aggs
  # POST /event_aggs.json
  def create
    @event_agg = EventAgg.new(event_agg_params)

    respond_to do |format|
      if @event_agg.save
        format.html { 
          redirect_to :controller => 'events_parsers', :action => 'new', :event_agg_id => @event_agg.id,
          notice: 'Event agg was successfully created.' 
        }
        format.json { render action: 'show', status: :created, location: @event_agg }
      else
        format.html { render action: 'new' }
        format.json { render json: @event_agg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_aggs/1
  # PATCH/PUT /event_aggs/1.json
  def update
    respond_to do |format|
      if @event_agg.update(event_agg_params)
        format.html { 
          redirect_to :controller => 'events_parsers', :action => 'new', :event_agg_id => @event_agg.id,
          notice: 'Event agg was successfully created.' 
        }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event_agg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_aggs/1
  # DELETE /event_aggs/1.json
  def destroy
    @event_agg.destroy
    respond_to do |format|
      format.html { redirect_to event_aggs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_agg
      @event_agg = EventAgg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_agg_params
      params.require(:event_agg).permit(:name, :url, :site_type, :pagination, :domain, :eventDetailsPageLink_xpath)
    end
end

app/controllers/events_parsers_controller.rb
class EventsParsersController < ApplicationController
  before_action :set_events_parser, only: [:show, :edit, :update, :destroy]

  # GET /events_parsers
  # GET /events_parsers.json
  def index
    @events_parsers = EventsParser.all
  end

  # GET /events_parsers/1
  # GET /events_parsers/1.json
  def show
  end

  # GET /events_parsers/new
  def new
    agg_id = params[:event_agg_id]

    @events_parser = EventsParser.new
    @events_parser.event_agg_id = agg_id
  end

  # GET /events_parsers/1/edit
  def edit
    agg_id = params[:event_agg_id]

  end

  # POST /events_parsers
  # POST /events_parsers.json
  def create
    @events_parser = EventsParser.new(events_parser_params)

    respond_to do |format|
      if @events_parser.save
        format.html { redirect_to @events_parser, notice: 'Events parser was successfully created.' }
        format.json { render action: 'show', status: :created, location: @events_parser }
      else
        format.html { render action: 'new' }
        format.json { render json: @events_parser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events_parsers/1
  # PATCH/PUT /events_parsers/1.json
  def update
    respond_to do |format|
      if @events_parser.update(events_parser_params)
        format.html { redirect_to @events_parser, notice: 'Events parser was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @events_parser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events_parsers/1
  # DELETE /events_parsers/1.json
  def destroy
    @events_parser.destroy
    respond_to do |format|
      format.html { redirect_to events_parsers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_events_parser
      @events_parser = EventsParser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def events_parser_params
      params.require(:events_parser).permit(:eventName_xpath, :eventLocation_xpath, :eventDateTime_xpath, :eventDescription_xpath, :eventPrice_xpath, :eventImage_xpath)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_aggs_helper.rb
module EventAggsHelper
end

app/helpers/events_parsers_helper.rb
module EventsParsersHelper
end

app/views/event_aggs/_form.html.erb
<%= form_for(@event_agg) do |f| %>
  <% if @event_agg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_agg.errors.count, "error") %> prohibited this event_agg from being saved:</h2>

      <ul>
      <% @event_agg.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :site_type %><br>
    <%= f.number_field :site_type %>
  </div>
  <div class="field">
    <%= f.label :pagination %><br>
    <%= f.text_field :pagination %>
  </div>
  <div class="field">
    <%= f.label :domain %><br>
    <%= f.text_field :domain %>
  </div>
  <div class="field">
    <%= f.label :eventDetailsPageLink_xpath %><br>
    <%= f.text_field :eventDetailsPageLink_xpath %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/event_aggs/edit.html.erb
<h1>Editing event_agg</h1>

<%= render 'form' %>

<%= link_to 'Show', @event_agg %> |
<%= link_to 'Back', event_aggs_path %>

app/views/event_aggs/index.html.erb
<h1>Listing event_aggs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Site type</th>
      <th>Pagination</th>
      <th>Domain</th>
      <th>Eventdetailspagelink xpath</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @event_aggs.each do |event_agg| %>
      <tr>
        <td><%= event_agg.name %></td>
        <td><%= event_agg.url %></td>
        <td><%= event_agg.site_type %></td>
        <td><%= event_agg.pagination %></td>
        <td><%= event_agg.domain %></td>
        <td><%= event_agg.eventDetailsPageLink_xpath %></td>
        <td><%= link_to 'Show', event_agg %></td>
        <td><%= link_to 'Edit', edit_event_agg_path(event_agg) %></td>
        <td><%= link_to 'Destroy', event_agg, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event agg', new_event_agg_path %>

app/views/event_aggs/new.html.erb
<h1>New event_agg</h1>

<%= render 'form' %>

<%= link_to 'Back', event_aggs_path %>

app/views/event_aggs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event_agg.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @event_agg.url %>
</p>

<p>
  <strong>Site type:</strong>
  <%= @event_agg.site_type %>
</p>

<p>
  <strong>Pagination:</strong>
  <%= @event_agg.pagination %>
</p>

<p>
  <strong>Domain:</strong>
  <%= @event_agg.domain %>
</p>

<p>
  <strong>Eventdetailspagelink xpath:</strong>
  <%= @event_agg.eventDetailsPageLink_xpath %>
</p>

<%= link_to 'Edit', edit_event_agg_path(@event_agg) %> |
<%= link_to 'Back', event_aggs_path %>

app/views/events_parsers/_form.html.erb
<%= form_for(@events_parser) do |f| %>
  <% if @events_parser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@events_parser.errors.count, "error") %> prohibited this events_parser from being saved:</h2>

      <ul>
      <% @events_parser.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :eventName_xpath %><br>
    <%= f.text_area :eventName_xpath %>
  </div>
  <div class="field">
    <%= f.label :eventLocation_xpath %><br>
    <%= f.text_area :eventLocation_xpath %>
  </div>
  <div class="field">
    <%= f.label :eventDateTime_xpath %><br>
    <%= f.text_area :eventDateTime_xpath %>
  </div>
  <div class="field">
    <%= f.label :eventDescription_xpath %><br>
    <%= f.text_area :eventDescription_xpath %>
  </div>
  <div class="field">
    <%= f.label :eventPrice_xpath %><br>
    <%= f.text_area :eventPrice_xpath %>
  </div>
  <div class="field">
    <%= f.label :eventImage_xpath %><br>
    <%= f.text_area :eventImage_xpath %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events_parsers/edit.html.erb
<h1>Editing events_parser</h1>

<%= render 'form' %>

<%= link_to 'Show', @events_parser %> |
<%= link_to 'Back', events_parsers_path %>

app/views/events_parsers/index.html.erb
<h1>Listing events_parsers</h1>

<table>
  <thead>
    <tr>
      <th>Eventname xpath</th>
      <th>Eventlocation xpath</th>
      <th>Eventdatetime xpath</th>
      <th>Eventdescription xpath</th>
      <th>Eventprice xpath</th>
      <th>Eventimage xpath</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events_parsers.each do |events_parser| %>
      <tr>
        <td><%= events_parser.eventName_xpath %></td>
        <td><%= events_parser.eventLocation_xpath %></td>
        <td><%= events_parser.eventDateTime_xpath %></td>
        <td><%= events_parser.eventDescription_xpath %></td>
        <td><%= events_parser.eventPrice_xpath %></td>
        <td><%= events_parser.eventImage_xpath %></td>
        <td><%= link_to 'Show', events_parser %></td>
        <td><%= link_to 'Edit', edit_events_parser_path(events_parser) %></td>
        <td><%= link_to 'Destroy', events_parser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Events parser', new_events_parser_path %>

app/views/events_parsers/new.html.erb
<h1>New events_parser</h1>

<%= render 'form' %>

<%= link_to 'Back', events_parsers_path %>

app/views/events_parsers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Eventname xpath:</strong>
  <%= @events_parser.eventName_xpath %>
</p>

<p>
  <strong>Eventlocation xpath:</strong>
  <%= @events_parser.eventLocation_xpath %>
</p>

<p>
  <strong>Eventdatetime xpath:</strong>
  <%= @events_parser.eventDateTime_xpath %>
</p>

<p>
  <strong>Eventdescription xpath:</strong>
  <%= @events_parser.eventDescription_xpath %>
</p>

<p>
  <strong>Eventprice xpath:</strong>
  <%= @events_parser.eventPrice_xpath %>
</p>

<p>
  <strong>Eventimage xpath:</strong>
  <%= @events_parser.eventImage_xpath %>
</p>

<%= link_to 'Edit', edit_events_parser_path(@events_parser) %> |
<%= link_to 'Back', events_parsers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuperScraper</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>